/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../modules/auth/components/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/profile/components/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/profile/index`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/auth/index`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/rooms/index`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/rooms/components/RoomCard`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/rooms/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/rooms/hooks/useRoomSearch`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../modules/auth/components/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../modules/profile/components/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../modules/profile/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../modules/auth/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../modules/rooms/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../modules/rooms/components/RoomCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../modules/rooms/components/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/../modules/rooms/hooks/useRoomSearch`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../modules/auth/components/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/../modules/profile/components/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/../modules/profile/index${`?${string}` | `#${string}` | ''}` | `/../modules/auth/index${`?${string}` | `#${string}` | ''}` | `/../modules/rooms/index${`?${string}` | `#${string}` | ''}` | `/../modules/rooms/components/RoomCard${`?${string}` | `#${string}` | ''}` | `/../modules/rooms/components/SearchBar${`?${string}` | `#${string}` | ''}` | `/../modules/rooms/hooks/useRoomSearch${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../modules/auth/components/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/profile/components/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/profile/index`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/auth/index`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/rooms/index`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/rooms/components/RoomCard`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/rooms/components/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/../modules/rooms/hooks/useRoomSearch`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
